//! `BlendPass::gl_resources_free` deleting its material's compiled program.
//!
//! wasm32-only: every assertion asks a real `WebGl2RenderingContext` whether a
//! GL object still exists, which a native `cargo nextest` run cannot answer —
//! constructing the subject at all needs a live context. The headless-browser
//! runner in `.cargo/config.toml` is what executes these.
//!
//! Freeing a GPU resource is invisible from the Rust side: a handle wrapper is
//! a JS-object reference, so letting it go out of scope reclaims nothing. Only
//! asking the context — `gl.is_texture`, `gl.is_framebuffer` — distinguishes a
//! resource that was released from one that merely stopped being referenced,
//! which is why these tests hold handle clones across the drop.

use minwebgl as gl;
use ::renderer::webgl::post_processing::BlendPass;

fn gl_init() -> gl::WebGl2RenderingContext
{
  gl::browser::setup( gl::browser::Config::default() );
  let options = gl::context::ContextOptions::default();
  let canvas = gl::canvas::make().unwrap();
  gl::context::from_canvas_with( &canvas, options ).unwrap()
}

/// ## Root Cause
/// `BlendPass` held a compiled program with no way to free it -- `Renderer`'s new
/// full-teardown method ( `Renderer::gl_resources_free`, BUG-434 ) could never be complete
/// while its `blend_effect: BlendPass` field had no cleanup path of its own.
///
/// ## Why Not Caught
/// `BlendPass` had zero prior test coverage -- no test previously constructed one to check
/// for a leaked program.
///
/// ## Fix Applied
/// Added `pub fn gl_resources_free`, deleting `material`'s compiled program via
/// `ShaderProgram::program()`. `Renderer::gl_resources_free` now delegates to it (see
/// `renderer.rs`'s own inline test for the composite/skybox portion of the same fix).
///
/// ## Prevention
/// This test captures `material`'s program handle before calling `gl_resources_free`, then
/// asserts the program is deleted afterward.
///
/// ## Pitfall
/// `material` is a `ShaderProgram` impl generated by `impl_locations!`, which has no
/// `gl_resources_free`/`Drop` of its own -- program cleanup for any type built on that
/// macro always has to happen one level up, at the owning struct.
// test_kind: bug_reproducer(BUG-434)
#[ wasm_bindgen_test::wasm_bindgen_test ]
fn blend_pass_gl_resources_free_deletes_material_program()
{
  let gl = gl_init();
  let mut pass = BlendPass::new( &gl ).expect( "BlendPass::new should succeed on a valid context" );

  let program = pass.material_program_for_test();
  assert!( gl.is_program( Some( &program ) ) );

  pass.gl_resources_free( &gl );

  assert!( !gl.is_program( Some( &program ) ), "gl_resources_free must delete material's program" );
}
