[package]
name = "cg_tools"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"
rust-version = "1.81.0"
repository = "https://github.com/Wandalen/cg_tools"
description = "Computer Graphics Toolkit"
readme = "readme.md"
keywords = ["wasm", "cg"]

[lints]
workspace = true

[features]
enabled = [
  "dep:mod_interface",
]
default = [ "enabled" ]
full = [ "default" ]

[dependencies]

mod_interface = { workspace = true, optional = true }
