[package]
name = "minwgpu_sun_grid_lines"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu.workspace = true
image.workspace = true
minwgpu.workspace = true
bytemuck = { workspace = true, features = [ "derive" ] }

[lints]
workspace = true

[package.metadata.action]
tags = ["runtime:offscreen", "api:wgpu"]
