/// Internal namespace.
mod private
{
  // use crate::*;

}

crate::mod_interface!
{
  // error_tools 0.41 is no longer a mod_interface layer (no own/exposed namespaces),
  // so `reuse ::error_tools as error` stopped resolving; re-export its surface explicitly.
  /// Typed error handling, a facade for `thiserror` (`error::typed::Error` derive).
  own use ::error_tools::error::typed;
  /// Untyped error handling, a facade for `anyhow`.
  own use ::error_tools::error::untyped;
  /// The `thiserror` crate itself — code generated by the `Error` derive resolves this
  /// name, so it must propagate into consumer crate roots (hence `exposed`, not `own`).
  exposed use ::error_tools::dependency::thiserror;
}
