[package]
name = "minwebgl_minimize_wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

minwebgl = { workspace = true, features = [ "future", "math", "diagnostics" ] }
wee_alloc = { workspace = true }

[package.metadata.action]
tags = ["runtime:browser", "api:webgl"]

[lints]
workspace = true
