[package]
name = "minwebgl_minimize_wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
minwebgl = { workspace = true }
cgmath = { workspace = true } # xxx : qqq : remove such dependencies
wee_alloc = { workspace = true }
