[package]
name = "minwebgl_minimize_wasm"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]

minwebgl = { workspace = true, features = [ "future", "math", "diagnostics" ] }
wee_alloc = { workspace = true }

# minwebgl = "0.2"
# cgmath = "0.18.0"
# wee_alloc = "0.4"
