//! Real, browser-executed test of `gpu_hal`'s WebGL backend -- constructs a
//! live `Device`/`Queue`/`Surface` via `Device::new_webgl`, draws the same
//! uniform-colored triangle `native_backend_test.rs::triangle_render_readback`
//! draws, and asserts on pixels read back from the canvas. `webgl_build_test.rs`
//! looks adjacent but only checks WGSL->GLSL string translation -- no live GL
//! context, no canvas, no draw call; this file is the one that actually proves
//! the backend renders.
//!
//! `Surface::pixels_read` is `Unsupported` for this backend by design (browser
//! surfaces present to their canvas instead of offering an offscreen copy --
//! see `device.rs` and `pixels_read_is_unsupported_on_the_webgl_surface` below),
//! so readback here goes through the live `GL` context directly via
//! `Surface::as_webgl` + `read_pixels`, the same context `pass.end()` leaves
//! bound to the canvas's default framebuffer.

#![ cfg( all( feature = "webgl", target_arch = "wasm32" ) ) ]

use gpu_hal::*;
use wasm_bindgen_test::wasm_bindgen_test;

// Browser, not Node: constructing a WebGL2 context needs a real canvas.
wasm_bindgen_test::wasm_bindgen_test_configure!( run_in_browser );

use minwebgl as gl;

/// Bytes of a `f32` slice, little-endian -- mirrors `native_backend_test.rs::as_bytes`.
fn as_bytes( values : &[ f32 ] ) -> Vec< u8 >
{
  values.iter().flat_map( | v | v.to_le_bytes() ).collect()
}

/// Uniform-colored triangle, the same WGSL `native_backend_test.rs`'s
/// `triangle_render_readback` uses. The WebGl arm of `shader_module_create`
/// never reads this field -- it requires both GLSL overrides below instead --
/// kept here anyway so `ShaderSource` stays honest about what the pipeline
/// conceptually runs, the same choice `triangle_browser`'s example makes.
const WGSL : &str = "
struct Color
{
  value : vec4f,
}

@group( 0 ) @binding( 0 )
var< uniform > color : Color;

@vertex
fn vs_main( @location( 0 ) position : vec2f ) -> @builtin( position ) vec4f
{
  return vec4f( position, 0.0, 1.0 );
}

@fragment
fn fs_main() -> @location( 0 ) vec4f
{
  return color.value;
}
";

/// GLSL ES 300 vertex stage, hand-written rather than generated by
/// `webgl_build::wgsl_to_webgl_glsl` -- that function's own doc comment states
/// it is a `build.rs`-time-only tool whose `naga` dependency must never enter
/// a compiled wasm32 artifact, which is exactly what calling it from this test
/// at runtime would do.
const GLSL_VERTEX : &str = "#version 300 es
layout( location = 0 ) in vec2 position;

void main()
{
  gl_Position = vec4( position, 0.0, 1.0 );
}
";

/// GLSL ES 300 fragment stage -- the uniform block is named `ub_0_0` per
/// `webgl_bindings_introspect`'s `ub_{group}_{binding}` convention
/// (`device.rs`), matching `WGSL`'s `@group(0) @binding(0)`.
const GLSL_FRAGMENT : &str = "#version 300 es
precision highp float;

layout( std140 ) uniform ub_0_0
{
  vec4 value;
};

out vec4 frag_color;

void main()
{
  frag_color = value;
}
";

/// Creates a canvas sized exactly `width`x`height`. `minwebgl::canvas::make`
/// wires up a `ResizeObserver` that continuously re-sizes the drawing buffer
/// from ambient `client_width`/`client_height` * device-pixel-ratio, which is
/// not deterministic for a pixel-asserting test -- the explicit `set_width`/
/// `set_height` below overrides that, and nothing between here and the render
/// pass yields to the event loop, so the observer never gets a chance to
/// override it back before `webgl_canvas_pass_begin` reads the drawing buffer
/// size.
fn canvas_make( width : u32, height : u32 ) -> gl::web_sys::HtmlCanvasElement
{
  gl::browser::setup( gl::browser::Config::default() );
  let canvas = gl::canvas::make().expect( "canvas creation failed" );
  canvas.set_width( width );
  canvas.set_height( height );
  canvas
}

#[ wasm_bindgen_test ]
fn device_creation()
{
  let canvas = canvas_make( 64, 64 );
  let ( device, _queue, surface ) = Device::new_webgl( &canvas )
  .expect( "webgl device creation failed -- does this browser support WebGL2 + EXT_color_buffer_float?" );
  assert_eq!( device.depth_range(), DepthRange::NegOneToOne );
  assert_eq!( surface.format(), TextureFormat::Rgba8Unorm );
}

#[ wasm_bindgen_test ]
fn pixels_read_is_unsupported_on_the_webgl_surface()
{
  let canvas = canvas_make( 4, 4 );
  let ( device, queue, surface ) = Device::new_webgl( &canvas )
  .expect( "webgl device creation failed" );
  let result = surface.pixels_read( &device, &queue );
  assert!
  (
    matches!( result, Err( Error::Unsupported( _ ) ) ),
    "browser surfaces present to their canvas -- pixels_read must stay Unsupported, not silently \
    start returning data (which would mean this file's own read_pixels path below is now dead code)"
  );
}

/// Resources for `triangle_render_readback`, built once and drawn from --
/// factored out of the test body to keep every function here well under the
/// repo's function-length norm (`triangle_draw` in `triangle_browser`'s own
/// example was rejected during its acceptance walk for growing past it --
/// see `task/verified/191_gpu_hal_browser_pixel_verification.md`).
struct TriangleScene
{
  device : Device,
  queue : Queue,
  surface : Surface,
  pipeline : RenderPipeline,
  bind_group : BindGroup,
  vertex_buffer : Buffer,
  index_buffer : Buffer,
}

/// Builds the device, pipeline, and buffers for a single uniform-red triangle
/// over a `width`x`height` canvas.
fn triangle_scene_setup( width : u32, height : u32 ) -> TriangleScene
{
  let canvas = canvas_make( width, height );
  let ( device, queue, surface ) = Device::new_webgl( &canvas )
  .expect( "webgl device creation failed -- does this browser support WebGL2 + EXT_color_buffer_float?" );

  let shader = device.shader_module_create( &ShaderSource
  {
    wgsl : WGSL,
    glsl_vertex : Some( GLSL_VERTEX ),
    glsl_fragment : Some( GLSL_FRAGMENT )
  } )
  .expect( "shader module creation failed" );

  let vertices = as_bytes( &[ -0.5, -0.5, 0.5, -0.5, 0.0, 0.5 ] );
  let vertex_buffer = device.buffer_init_create( &vertices, BufferUsage::VERTEX )
  .expect( "vertex buffer creation failed" );
  let indices : Vec< u8 > = [ 0u32, 1, 2 ].iter().flat_map( | i | i.to_le_bytes() ).collect();
  let index_buffer = device.buffer_init_create( &indices, BufferUsage::INDEX )
  .expect( "index buffer creation failed" );

  let uniform_buffer = device.buffer_create( 16, BufferUsage::UNIFORM | BufferUsage::COPY_DST )
  .expect( "uniform buffer creation failed" );
  queue.buffer_write( &uniform_buffer, &as_bytes( &[ 1.0, 0.0, 0.0, 1.0 ] ) )
  .expect( "uniform write failed" );

  let layout = device.bind_group_layout_create
  (
    &[ BindGroupLayoutEntry { visibility : ShaderStages::FRAGMENT, ty : BindingType::UniformBuffer } ]
  )
  .expect( "bind group layout creation failed" );
  let bind_group = device.bind_group_create( &layout, &[ BindingResource::Buffer( &uniform_buffer ) ] )
  .expect( "bind group creation failed" );

  let pipeline = pipeline_create( &device, &shader, &layout, surface.format() );

  TriangleScene { device, queue, surface, pipeline, bind_group, vertex_buffer, index_buffer }
}

/// Builds the render pipeline for the single `vec2` vertex position attribute
/// and one fragment-stage uniform block `triangle_scene_setup` wires up --
/// split out to keep both functions under the repo's function-length norm
/// (see `TriangleScene`'s own doc comment for why that norm is enforced here).
fn pipeline_create
(
  device : &Device,
  shader : &ShaderModule,
  layout : &BindGroupLayout,
  color_format : TextureFormat
) -> RenderPipeline
{
  device.render_pipeline_create( &RenderPipelineDesc
  {
    shader,
    vertex_entry : "vs_main",
    fragment_entry : "fs_main",
    vertex_buffers : &[ VertexBufferLayout
    {
      stride : 8,
      step_mode : StepMode::Vertex,
      attributes : vec! [ VertexAttribute { location : 0, format : VertexFormat::Float32x2, offset : 0 } ]
    } ],
    bind_group_layouts : &[ layout ],
    color_format,
    depth : None,
    cull_back : false
  } )
  .expect( "pipeline creation failed" )
}

/// Draws `scene`'s triangle over a black clear -- the render-pass half of
/// `native_backend_test.rs::triangle_render_readback`, unchanged in shape,
/// against a WebGL-backed `Device`/`Queue`/`Surface` triple instead of
/// native's offscreen wgpu one.
fn triangle_render( scene : &TriangleScene )
{
  let view = scene.surface.current_view().expect( "surface view unavailable" );
  let mut encoder = scene.device.command_encoder_create();
  let mut pass = encoder.render_pass_begin
  (
    &ColorAttachmentDesc { view : &view, clear : [ 0.0, 0.0, 0.0, 1.0 ] },
    None
  )
  .expect( "render pass failed to begin" );
  pass.pipeline_set( &scene.pipeline );
  pass.bind_group_set( 0, &scene.bind_group );
  pass.vertex_buffer_set( 0, &scene.vertex_buffer );
  pass.index_buffer_set( &scene.index_buffer, IndexFormat::Uint32 );
  pass.draw_indexed( 3 );
  pass.end();
  scene.queue.submit( encoder );
}

/// Reads the canvas backbuffer back as tightly-packed rgba8 bytes.
/// `Surface::pixels_read` is `Unsupported` on this backend (see
/// `pixels_read_is_unsupported_on_the_webgl_surface` above), so this goes
/// through the live `GL` context directly -- the same one `pass.end()` leaves
/// bound to the default framebuffer, since `webgl_canvas_pass_begin` records
/// `fbo : None` for canvas passes and `end()` only ever deletes a `Some` one.
fn canvas_pixels_read( surface : &Surface, width : u32, height : u32 ) -> Vec< u8 >
{
  let context = surface.as_webgl().expect( "as_webgl must return Some on a Surface::WebGl handle" );
  let out = gl::js_sys::Uint8Array::new_with_length( width * height * 4 );
  context.read_pixels_with_array_buffer_view_and_dst_offset
  (
    0, 0, width as i32, height as i32, gl::RGBA, gl::UNSIGNED_BYTE, &out, 0
  )
  .expect( "read_pixels should succeed on the canvas backbuffer" );
  out.to_vec()
}

#[ wasm_bindgen_test ]
fn triangle_render_readback()
{
  let width = 100u32;
  let height = 100u32;
  let scene = triangle_scene_setup( width, height );
  triangle_render( &scene );
  let pixels = canvas_pixels_read( &scene.surface, width, height );
  assert_eq!( pixels.len(), ( width * height * 4 ) as usize );

  // WebGL's `readPixels` fills bottom row first -- the opposite of
  // `native_backend_test.rs`'s documented top-row-first wgpu convention.
  // Immaterial to the two samples below: pixel (50,50) sits on the buffer's
  // exact middle row, which lands on the same physical row (up to a
  // harmless off-by-one) under either convention, so it stays inside the
  // triangle either way; pixel (0,0) sits on a buffer corner that maps to
  // one of the canvas's two top/bottom corners depending on convention, and
  // the triangle is small and centered enough that both candidate corners
  // lie outside it either way.
  let at = | x : u32, y : u32 |
  {
    let start = ( ( y * width + x ) * 4 ) as usize;
    [ pixels[ start ], pixels[ start + 1 ], pixels[ start + 2 ], pixels[ start + 3 ] ]
  };
  assert_eq!( at( 50, 50 ), [ 255, 0, 0, 255 ], "center pixel should be the uniform's red" );
  assert_eq!( at( 0, 0 ), [ 0, 0, 0, 255 ], "corner pixel should be the clear color" );
}
