
mod private
{
  use minwebgl as gl;
  use crate::webgl::{ ShaderProgram, post_processing::{ Pass, VS_TRIANGLE }, program::EmptyShader };

  /// A post-processing pass designed to blend a source texture (`blend_texture`)
  /// onto a destination texture (`output_texture`) using specified blending parameters.
  pub struct BlendPass
  {
    /// The source blending factor
    pub src_factor : u32,
    /// The destination blending factor
    pub dst_factor : u32,
    /// The blending equation, specifying how source and destination components are combined.
    pub equation : u32,
    /// The WebGL program used for the blending operation.
    material : EmptyShader,
    /// The texture that will be blended onto the `output_texture`. This is the source
    pub blend_texture : Option< gl::web_sys::WebGlTexture >
  }

  impl BlendPass
  {
    /// Set the blending texture of the pass
    pub fn blend_texture_set( &mut self, texture : Option< gl::web_sys::WebGlTexture > )
    {
      self.blend_texture = texture;
    }

    /// Creates a new `BlendPass` instance with default blending parameters.
    ///
    /// By default, it sets up alpha blending (`gl::SRC_ALPHA`, `gl::ONE_MINUS_SRC_ALPHA`)
    /// with an additive equation (`gl::FUNC_ADD`). The `blend_texture` is initially `None`.
    ///
    /// # Errors
    ///
    /// Returns `WebglError` if the blend shader fails to compile or link.
    pub fn new( gl : &gl::WebGl2RenderingContext ) -> Result< Self, gl::WebglError >
    {
      let src_factor = gl::SRC_ALPHA;
      let dst_factor = gl::ONE_MINUS_SRC_ALPHA;
      let equation = gl::FUNC_ADD;
      let blend_texture = None;

      let fs_shader = include_str!( "../shaders/copy.frag" );
      let material = gl::ProgramFromSources::new( VS_TRIANGLE, fs_shader ).compile_and_link( gl )?;
      let material = EmptyShader::new( gl, &material );

      Ok
      (
        Self
        {
          src_factor,
          dst_factor,
          equation,
          material,
          blend_texture
        }
      )
    }

    /// Frees the WebGL program backing this pass's shader.
    ///
    /// # Fix(BUG-434)
    /// `BlendPass` held a compiled program with no way to free it, so `Renderer`'s new
    /// full-teardown method ( `Renderer::gl_resources_free` ) could never be complete.
    /// Root cause: `BlendPass` was written before any struct in this crate needed a
    /// full-teardown path, so `material` was simply never freed anywhere.
    /// Pitfall: `material` is a `ShaderProgram` impl generated by `impl_locations!`, which
    /// has no `gl_resources_free`/`Drop` of its own — program cleanup has to happen here,
    /// one level up, via `ShaderProgram::program()`.
    pub fn gl_resources_free( &mut self, gl : &gl::WebGl2RenderingContext )
    {
      gl.delete_program( Some( self.material.program() ) );
    }
  }

  impl Pass for BlendPass
  {
    fn renders_to_input( &self ) -> bool
    {
      true
    }

    /// Blends the `self.blend_texture` with the `output_texture`, setting the `output_texture` as destination
    fn render
    (
        &self,
        gl : &minwebgl::WebGl2RenderingContext,
        _input_texture : Option< minwebgl::web_sys::WebGlTexture >,
        output_texture : Option< minwebgl::web_sys::WebGlTexture >
    ) -> Result< Option< minwebgl::web_sys::WebGlTexture >, minwebgl::WebglError >
    {
      gl.disable( gl::DEPTH_TEST );
      // Screen-space pass: the fullscreen triangle is back-facing, so it must not
      // inherit the scene's CULL_FACE state or it gets culled and nothing draws.
      gl.disable( gl::CULL_FACE );
      gl.enable( gl::BLEND );
      gl.blend_equation( self.equation );
      gl.blend_func( self.src_factor, self.dst_factor );

      // Bind the copy shader.
      self.material.bind( gl );
      gl.active_texture( gl::TEXTURE0 );
      gl.bind_texture( gl::TEXTURE_2D, self.blend_texture.as_ref() );
      gl.framebuffer_texture_2d
      (
        gl::FRAMEBUFFER,
        gl::COLOR_ATTACHMENT0,
        gl::TEXTURE_2D,
        output_texture.as_ref(),
        0
      );
      gl.draw_arrays( gl::TRIANGLES, 0, 3 );

      // --- Cleanup ---
      // Unbind the texture and framebuffer attachment to restore default state.
      gl::clean::texture_2d( gl );
      gl::clean::framebuffer_texture_2d( gl );

      Ok
      (
        output_texture
      )
    }
  }

  // Test placement: verifying `gl_resources_free` deleted `material`'s program needs the
  // pre-call handle, and `material` is private -- only a test nested inside `mod private` can
  // read it. See `rulebook.md § Test placement`.
  #[ cfg( all( test, target_arch = "wasm32" ) ) ]
  mod tests
  {
    use super::*;

    fn gl_init() -> gl::WebGl2RenderingContext
    {
      gl::browser::setup( gl::browser::Config::default() );
      let options = gl::context::ContextOptions::default();
      let canvas = gl::canvas::make().unwrap();
      gl::context::from_canvas_with( &canvas, options ).unwrap()
    }

    /// ## Root Cause
    /// `BlendPass` held a compiled program with no way to free it -- `Renderer`'s new
    /// full-teardown method ( `Renderer::gl_resources_free`, BUG-434 ) could never be complete
    /// while its `blend_effect: BlendPass` field had no cleanup path of its own.
    ///
    /// ## Why Not Caught
    /// `BlendPass` had zero prior test coverage -- no test previously constructed one to check
    /// for a leaked program.
    ///
    /// ## Fix Applied
    /// Added `pub fn gl_resources_free`, deleting `material`'s compiled program via
    /// `ShaderProgram::program()`. `Renderer::gl_resources_free` now delegates to it (see
    /// `renderer.rs`'s own inline test for the composite/skybox portion of the same fix).
    ///
    /// ## Prevention
    /// This test captures `material`'s program handle before calling `gl_resources_free`, then
    /// asserts the program is deleted afterward.
    ///
    /// ## Pitfall
    /// `material` is a `ShaderProgram` impl generated by `impl_locations!`, which has no
    /// `gl_resources_free`/`Drop` of its own -- program cleanup for any type built on that
    /// macro always has to happen one level up, at the owning struct.
    // test_kind: bug_reproducer(BUG-434)
    #[ wasm_bindgen_test::wasm_bindgen_test ]
    fn blend_pass_gl_resources_free_deletes_material_program()
    {
      let gl = gl_init();
      let mut pass = BlendPass::new( &gl ).expect( "BlendPass::new should succeed on a valid context" );

      let program = pass.material.program().clone();
      assert!( gl.is_program( Some( &program ) ) );

      pass.gl_resources_free( &gl );

      assert!( !gl.is_program( Some( &program ) ), "gl_resources_free must delete material's program" );
    }
  }
}

crate::mod_interface!
{
  orphan use
  {
    BlendPass
  };
}
