
mod private
{
  use minwebgl as gl;
  use crate::webgl::{ ShaderProgram, post_processing::{ Pass, VS_TRIANGLE }, program::EmptyShader };

  /// A post-processing pass designed to blend a source texture (`blend_texture`)
  /// onto a destination texture (`output_texture`) using specified blending parameters.
  pub struct BlendPass
  {
    /// The source blending factor
    pub src_factor : u32,
    /// The destination blending factor
    pub dst_factor : u32,
    /// The blending equation, specifying how source and destination components are combined.
    pub equation : u32,
    /// The WebGL program used for the blending operation.
    material : EmptyShader,
    /// The texture that will be blended onto the `output_texture`. This is the source
    pub blend_texture : Option< gl::web_sys::WebGlTexture >
  }

  impl BlendPass
  {
    /// Set the blending texture of the pass
    pub fn blend_texture_set( &mut self, texture : Option< gl::web_sys::WebGlTexture > )
    {
      self.blend_texture = texture;
    }

    /// Creates a new `BlendPass` instance with default blending parameters.
    ///
    /// By default, it sets up alpha blending (`gl::SRC_ALPHA`, `gl::ONE_MINUS_SRC_ALPHA`)
    /// with an additive equation (`gl::FUNC_ADD`). The `blend_texture` is initially `None`.
    ///
    /// # Errors
    ///
    /// Returns `WebglError` if the blend shader fails to compile or link.
    pub fn new( gl : &gl::WebGl2RenderingContext ) -> Result< Self, gl::WebglError >
    {
      let src_factor = gl::SRC_ALPHA;
      let dst_factor = gl::ONE_MINUS_SRC_ALPHA;
      let equation = gl::FUNC_ADD;
      let blend_texture = None;

      let fs_shader = include_str!( "../shaders/copy.frag" );
      let material = gl::ProgramFromSources::new( VS_TRIANGLE, fs_shader ).compile_and_link( gl )?;
      let material = EmptyShader::new( gl, &material );

      Ok
      (
        Self
        {
          src_factor,
          dst_factor,
          equation,
          material,
          blend_texture
        }
      )
    }

    /// Frees the WebGL program backing this pass's shader.
    ///
    /// # Fix(BUG-434)
    /// `BlendPass` held a compiled program with no way to free it, so `Renderer`'s new
    /// full-teardown method ( `Renderer::gl_resources_free` ) could never be complete.
    /// Root cause: `BlendPass` was written before any struct in this crate needed a
    /// full-teardown path, so `material` was simply never freed anywhere.
    /// Pitfall: `material` is a `ShaderProgram` impl generated by `impl_locations!`, which
    /// has no `gl_resources_free`/`Drop` of its own — program cleanup has to happen here,
    /// one level up, via `ShaderProgram::program()`.
    pub fn gl_resources_free( &mut self, gl : &gl::WebGl2RenderingContext )
    {
      gl.delete_program( Some( self.material.program() ) );
    }
  }

  /// The program `gl_resources_free` deletes, reachable from `tests/` under
  /// `test_internals`. A clone, because a teardown test has to hold it across
  /// the free call to ask the context whether it is still live afterwards.
  #[ cfg( feature = "test_internals" ) ]
  impl BlendPass
  {
    #[ doc( hidden ) ]
    #[ must_use ]
    pub fn material_program_for_test( &self ) -> gl::web_sys::WebGlProgram
    {
      self.material.program().clone()
    }
  }

  impl Pass for BlendPass
  {
    fn renders_to_input( &self ) -> bool
    {
      true
    }

    /// Blends the `self.blend_texture` with the `output_texture`, setting the `output_texture` as destination
    fn render
    (
        &self,
        gl : &minwebgl::WebGl2RenderingContext,
        _input_texture : Option< minwebgl::web_sys::WebGlTexture >,
        output_texture : Option< minwebgl::web_sys::WebGlTexture >
    ) -> Result< Option< minwebgl::web_sys::WebGlTexture >, minwebgl::WebglError >
    {
      gl.disable( gl::DEPTH_TEST );
      // Screen-space pass: the fullscreen triangle is back-facing, so it must not
      // inherit the scene's CULL_FACE state or it gets culled and nothing draws.
      gl.disable( gl::CULL_FACE );
      gl.enable( gl::BLEND );
      gl.blend_equation( self.equation );
      gl.blend_func( self.src_factor, self.dst_factor );

      // Bind the copy shader.
      self.material.bind( gl );
      gl.active_texture( gl::TEXTURE0 );
      gl.bind_texture( gl::TEXTURE_2D, self.blend_texture.as_ref() );
      gl.framebuffer_texture_2d
      (
        gl::FRAMEBUFFER,
        gl::COLOR_ATTACHMENT0,
        gl::TEXTURE_2D,
        output_texture.as_ref(),
        0
      );
      gl.draw_arrays( gl::TRIANGLES, 0, 3 );

      // --- Cleanup ---
      // Unbind the texture and framebuffer attachment to restore default state.
      gl::clean::texture_2d( gl );
      gl::clean::framebuffer_texture_2d( gl );

      Ok
      (
        output_texture
      )
    }
  }
}

crate::mod_interface!
{
  orphan use
  {
    BlendPass
  };
}
