[package]
name = "browser_log"
version = "0.3.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"
rust-version = "1.81.0"
repository = "https://github.com/Wandalen/cg_tools"
description = "Utility to log in wasm/browser"
readme = "readme.md"
keywords = ["wasm"]

[lints]
workspace = true

[features]
enabled = [
  "dep:wasm-bindgen",
  "dep:web-sys",
  "dep:log",
  "dep:mod_interface",
]
default = [ "enabled" ]
full = [ "default" ]

[dependencies]

wasm-bindgen = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true, features = [
  'console',
]}
log = { workspace = true, optional = true, features = [ "std" ] }
mod_interface = { workspace = true, optional = true }

