[package]
name = "canvas_renderer"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"
authors = [
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Bilan Vadym <vadym.b@obox.systems>"
]
license = "MIT"
repository = "https://github.com/Wandalen/cgtools"
homepage = "https://github.com/Wandalen/cgtools/tree/master/module/helper/canvas_renderer"
documentation = "https://docs.rs/canvas_renderer"
description = "2D canvas renderer for WebGL applications with framebuffer rendering and 3D scene support"
readme = "readme.md"
keywords = ["webgl", "rendering", "canvas", "2d", "graphics"]
categories = ["graphics", "rendering", "web-programming", "game-development"]
include = [
    "src/**/*",
    "shaders/**/*",
    "tests/**/*",
    "Cargo.toml",
    "readme.md",
    "license*",
    "changelog*",
]

[lints]
workspace = true

[features]
default = ["enabled"]

# Core canvas rendering functionality
enabled = [
    "dep:mod_interface",
    "dep:minwebgl", 
    "dep:mingl",
    "dep:renderer",
    "dep:web-sys",
]

# Full feature set
full = ["enabled"]

[dependencies]
mod_interface = { workspace = true, optional = true }
minwebgl = { workspace = true, features = [ "future", "math", "diagnostics" ], optional = true }
mingl = { workspace = true, features = [ "camera_orbit_controls" ], optional = true }
renderer = { workspace = true, optional = true }

[dependencies.web-sys]
workspace = true
optional = true
features = [
  'MouseEvent',
  'PointerEvent',
  'WheelEvent',
  'WebGlTexture',
  'HtmlImageElement',
  'Blob',
  'BlobPropertyBag',
  'Url',
  'WebGlFramebuffer',
  'WebGlRenderbuffer'
]

[dev-dependencies]
test_tools = { workspace = true }

# Metadata for crates.io
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
default-target = "wasm32-unknown-unknown"
targets = [
    "wasm32-unknown-unknown",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
]

# Cargo.toml maintenance metadata
[package.metadata.release]
pre-release-replacements = [
    { file = "readme.md", search = "canvas_renderer = \"[0-9.]+\"", replace = "canvas_renderer = \"{{version}}\"" },
    { file = "changelog.md", search = "## Unreleased", replace = "## Unreleased\n\n## {{version}} - {{date}}" },
]
