[package]
name = "wave_function_collapse"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"

[dependencies]
minwebgl = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
rayon = { workspace = true }
getrandom = { workspace = true, features = [ "js" ] }
rand = { workspace = true, features = [ "small_rng" ] }
ndarray_cg = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
  'WebGlTexture',
  'CanvasRenderingContext2d',
  'HtmlImageElement',
  'DomRect'
]
