[package]
name = "wave_function_collapse"
version = "0.1.0"
edition = "2021"
authors = [ "Kostiantyn Mysnyk <wandalen@obox.systems>" ]
license = "MIT"

[dependencies]
minwebgl = { workspace = true }
serde = { workspace = true, features = [ "derive" ] } # Features already here
serde_json = { workspace = true } # Added features back (assuming default features are needed)
rayon = { workspace = true } # Added features back (assuming default features are needed)
getrandom = { workspace = true, features = [ "js" ] } # Features already here
rand = { workspace = true, features = [ "small_rng" ] } # Features already here
ndarray_cg = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [ # Features already here
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
  'WebGlTexture',
  'CanvasRenderingContext2d',
  'HtmlImageElement',
  'DomRect'
]
