[package]
name = "falling_frontier"
version = "0.1.0"
edition = "2024"

[dependencies]
minwebgl = { workspace = true }
mingl = { workspace = true, features = [ "camera_orbit_controls" ] }
renderer = { workspace = true }
line_tools = { workspace = true, features = [ "distance" ] }
primitive_generation = { workspace = true }
gpu_picking = { workspace = true }
rand = "0.10.2"
getrandom = { version = "0.4.3", features = [ "wasm_js" ] }

[dependencies.web-sys]
workspace = true
features = [
  'MouseEvent',
  'PointerEvent',
  'WheelEvent',
  'KeyboardEvent',
  'Element',
  'HtmlInputElement',
  'HtmlSelectElement',
  'HtmlButtonElement',
  'HtmlHeadElement',
  'Event',
  'Navigator',
  'Clipboard',
  'DomRect',
]

[package.metadata.action]
tags = ["runtime:browser", "api:webgl"]

[lints]
workspace = true
