[package]
name = "raycaster"
version = "0.1.0"
edition = "2021"

[dependencies]
minwebgl = { workspace = true }
mingl = { workspace = true }
bytemuck = { workspace = true }
browser_input = { workspace = true }

[package.metadata.action]
tags = ["runtime:browser", "api:webgl"]

[lints]
workspace = true
