[package]
name = "wfc"
version = "0.1.0"
edition = "2021"
authors = [ 
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Bilan Vadym <vadym.b@obox.systems>"
]
license = "MIT"

[dependencies]
image = { version = "0.24", features = ["rayon"] }
RustyXML = "0.3.0"
wfc = { workspace = true }
wfc_image = { workspace = true, features = ["parallel"] }
minwebgl = { workspace = true }
getrandom = { version = "0.2", features = [ "js" ] }
rand = { version = "0.8.5" }
ndarray_cg = { workspace = true }
quick-xml = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
  'WebGlTexture',
  'CanvasRenderingContext2d',
  'HtmlImageElement',
  'HtmlButtonElement',
  'DomRect',
  'HtmlInputElement', 
  'Event',
  'InputEvent',
  'File',
  'FileList',
  'FileReader',
]
