# Cargo configuration for cgtools workspace

[build]
# Enable WebGPU unstable APIs for web-sys
rustflags = ["--cfg", "web_sys_unstable_apis"]
rustdocflags = ["--cfg", "web_sys_unstable_apis"]

[target.wasm32-unknown-unknown]
# WebAssembly specific configuration
rustflags = ["--cfg", "web_sys_unstable_apis"]