//! Generates `$OUT_DIR/chunks.rs` — the bundled-chunk descriptor table
//! `CHUNKS` and its O(1) by-name lookup `chunk_get`, spliced into
//! `src/lib.rs`'s `mod private` by `include!` — from the repo-root `shader/`
//! collection, so adding a chunk there ( its `shader/<name>/<name>.wgsl`
//! plus its collection-index row ) needs no Rust edit in this crate.
//!
//! Membership comes from scanning the collection's chunk directories; row
//! order comes from the collection-index table in `shader/readme.md` — the
//! human-curated order every registry consumer observes ( the `shader_chunks`
//! CLI's default `sort::input` is documented as registry order ). The two
//! sources are cross-validated both ways, so a chunk directory absent from
//! the index table, or an index row without a chunk directory, fails the
//! build naming the offender — the collection index can never drift from the
//! collection itself.
//!
//! The `//@` manifest parsing here deliberately re-implements the minimal
//! subset of `src/lib.rs`'s `parse_*` functions ( a build script cannot call
//! into the crate it is building ); the `chunks_table_matches_each_manifest`
//! test holds every generated row equal to what the lib parsers read from
//! the same manifest, so the two implementations cannot silently drift.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{ Path, PathBuf };

fn main()
{
  let manifest_dir = std::env::var( "CARGO_MANIFEST_DIR" ).expect( "cargo always sets CARGO_MANIFEST_DIR" );
  let shader_dir = PathBuf::from( &manifest_dir ).join( "../../../shader" );
  let shader_dir = shader_dir.canonicalize()
  .unwrap_or_else( | err | panic!( "cannot resolve shader collection dir {}: {err}", shader_dir.display() ) );

  // A directory path here makes cargo watch the whole tree recursively, so
  // any manifest, body, or collection-index edit regenerates the table.
  println!( "cargo::rerun-if-changed={}", shader_dir.display() );

  let scanned = chunk_dirs_scan( &shader_dir );
  let ordered = collection_index_order( &shader_dir, &scanned );

  let ( rows, arms ) : ( String, String ) = ordered.iter().enumerate().map( | ( i, name ) |
  {
    let wgsl_path = shader_dir.join( name ).join( format!( "{name}.wgsl" ) );
    let wgsl = std::fs::read_to_string( &wgsl_path )
    .unwrap_or_else( | err | panic!( "cannot read chunk source {}: {err}", wgsl_path.display() ) );
    ( descriptor_row( name, &wgsl, &wgsl_path ), format!( "    {name:?} => Some( &CHUNKS[ {i} ] ),\n" ) )
  })
  .unzip();

  let generated = format!
  (
r"// GENERATED by build.rs into $OUT_DIR — do not edit. Rebuilt from the
// repo-root `shader/` collection: one `ChunkDescriptor` row and one
// `chunk_get` match arm per `shader/<name>/<name>.wgsl` manifest, rows in
// collection-index order ( the table in `shader/readme.md` ). To add a
// chunk, add its directory and its index row — no Rust edit is needed. The
// `chunks_table_matches_each_manifest` test holds every generated field
// equal to what the lib's `parse_*` functions read from the same manifest.

/// Every bundled chunk, one [`ChunkDescriptor`] row per
/// `shader/<name>/<name>.wgsl` file, in collection-index order ( the table
/// in `shader/readme.md` ) — enumerate it directly, pass rows to
/// [`set_compose`]/[`set_try_compose`], or import single rows by name via
/// [`chunk`]. A `const` ( not `static` ) so [`chunk_get`] and [`chunk`] can
/// read it during compile-time evaluation.
pub const CHUNKS : &[ ChunkDescriptor ] =
&[
{rows}];

/// Resolves one bundled chunk by its manifest-declared name, in O(1) — a
/// static `match`, no table scan, no manifest parsing. Returns `None` for a
/// name not in [`CHUNKS`]. Runtime-only ( `str` match arms are not yet
/// const-stable ) — for `const`-position import use [`chunk`], which scans
/// [`CHUNKS`] during compile-time evaluation instead.
#[ must_use ]
pub fn chunk_get( name : &str ) -> Option< &'static ChunkDescriptor >
{{
  match name
  {{
{arms}    _ => None,
  }}
}}
"
  );

  let out_path = PathBuf::from( std::env::var( "OUT_DIR" ).expect( "cargo always sets OUT_DIR" ) ).join( "chunks.rs" );
  std::fs::write( &out_path, generated )
  .unwrap_or_else( | err | panic!( "cannot write generated chunk table {}: {err}", out_path.display() ) );
}

/// Every chunk directory name under `shader/` — each must hold its
/// `<name>.wgsl` chunk source, per the collection's own layout contract.
fn chunk_dirs_scan( shader_dir : &Path ) -> BTreeSet< String >
{
  let entries = std::fs::read_dir( shader_dir )
  .unwrap_or_else( | err | panic!( "cannot list shader collection dir {}: {err}", shader_dir.display() ) );
  let mut names = BTreeSet::new();
  for entry in entries
  {
    let entry = entry.unwrap_or_else( | err | panic!( "cannot read an entry of {}: {err}", shader_dir.display() ) );
    if !entry.file_type().is_ok_and( | file_type | file_type.is_dir() )
    {
      continue;
    }
    let name = entry.file_name().into_string()
    .unwrap_or_else( | raw | panic!( "non-UTF-8 chunk directory name {} in {}", raw.display(), shader_dir.display() ) );
    let wgsl_path = shader_dir.join( &name ).join( format!( "{name}.wgsl" ) );
    assert!
    (
      wgsl_path.is_file(),
      "chunk directory `{name}` has no {} — every `shader/` subdirectory must be a chunk",
      wgsl_path.display()
    );
    names.insert( name );
  }
  names
}

/// Chunk names in the order the collection-index table in
/// `shader/readme.md` lists them — a table row's first cell names its chunk
/// directory ( `[<name>/](...)` or bare `<name>/` ). Cross-validated both
/// ways against `scanned` so the index and the collection can never
/// disagree silently.
fn collection_index_order( shader_dir : &Path, scanned : &BTreeSet< String > ) -> Vec< String >
{
  let index_path = shader_dir.join( "readme.md" );
  let index = std::fs::read_to_string( &index_path )
  .unwrap_or_else( | err | panic!( "cannot read collection index {}: {err}", index_path.display() ) );

  let mut ordered = Vec::new();
  for line in index.lines()
  {
    let Some( rest ) = line.trim_start().strip_prefix( '|' ) else
    {
      continue;
    };
    let cell = rest.split( '|' ).next().unwrap_or( "" ).trim().trim_start_matches( '[' );
    let Some( ( name, _ ) ) = cell.split_once( '/' ) else
    {
      continue;
    };
    if name.is_empty() || !name.chars().all( | c | c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' )
    {
      continue;
    }
    ordered.push( name.to_string() );
  }

  let listed : BTreeSet< String > = ordered.iter().cloned().collect();
  assert_eq!
  (
    ordered.len(), listed.len(),
    "duplicate chunk row in the collection-index table {}", index_path.display()
  );
  if let Some( name ) = scanned.difference( &listed ).next()
  {
    panic!( "chunk directory `{name}` is missing from the collection-index table in {}", index_path.display() );
  }
  if let Some( name ) = listed.difference( scanned ).next()
  {
    panic!( "collection-index row `{name}` in {} has no `shader/{name}/` directory", index_path.display() );
  }
  ordered
}

/// One generated `ChunkDescriptor { ... },` block: every `//@` manifest
/// field of `wgsl` restated as Rust literals, plus an `include_str!` of the
/// chunk source anchored to `CARGO_MANIFEST_DIR` ( a path relative to the
/// generated file would resolve against `$OUT_DIR` ).
fn descriptor_row( name : &str, wgsl : &str, path : &Path ) -> String
{
  let manifest_name = manifest_field( wgsl, "name", path );
  assert_eq!
  (
    manifest_name, name,
    "chunk `{name}`: `//@ name:` value `{manifest_name}` must equal the directory and file-stem name ( {} )",
    path.display()
  );
  let description = manifest_field( wgsl, "description", path );
  let stage = manifest_field_opt( wgsl, "stage" );
  let depends_on = list_entries( manifest_field( wgsl, "depends_on", path ) );
  let exports = manifest_field_all( wgsl, "export" );
  let tags : Vec< ( &str, &str ) > = list_entries( manifest_field( wgsl, "tags", path ) )
  .into_iter()
  .map( | entry | entry.split_once( ':' )
    .unwrap_or_else( || panic!( "chunk `{name}`: malformed `//@ tags:` entry ( expected `group:tag` ): {entry:?}" ) ) )
  .collect();

  let tags_field = if tags.is_empty()
  {
    "&[]".to_string()
  }
  else
  {
    let pairs : Vec< String > = tags.iter().map( | ( group, tag ) | format!( "( {group:?}, {tag:?} )" ) ).collect();
    format!( "&[ {} ]", pairs.join( ", " ) )
  };
  let stage_field = match stage
  {
    None => "None".to_string(),
    Some( stage ) => format!( "Some( {stage:?} )" ),
  };
  let depends_field = if depends_on.is_empty()
  {
    "&[]".to_string()
  }
  else
  {
    let names : Vec< String > = depends_on.iter().map( | dep | format!( "{dep:?}" ) ).collect();
    format!( "&[ {} ]", names.join( ", " ) )
  };
  let exports_lines = if let [ only ] = exports.as_slice()
  {
    format!( "    exports : &[ {only:?} ],\n" )
  }
  else
  {
    let body = exports.iter().fold( String::new(), | mut body, export |
    {
      writeln!( body, "      {export:?}," ).expect( "writing to a String cannot fail" );
      body
    });
    format!( "    exports :\n    &[\n{body}    ],\n" )
  };
  let include_path = format!( "/../../../shader/{name}/{name}.wgsl" );
  format!
  (
r#"  ChunkDescriptor
  {{
    name : {name:?},
    description : {description:?},
    tags : {tags_field},
    stage : {stage_field},
    depends_on : {depends_field},
{exports_lines}    wgsl : include_str!( concat!( env!( "CARGO_MANIFEST_DIR" ), {include_path:?} ) ),
  }},
"#
  )
}

/// A mandatory single-line `//@ key: value` manifest field, trimmed.
fn manifest_field< 'a >( wgsl : &'a str, key : &str, path : &Path ) -> &'a str
{
  manifest_field_opt( wgsl, key )
  .unwrap_or_else( || panic!( "chunk {} is missing its required `//@ {key}:` header line", path.display() ) )
}

/// An optional single-line `//@ key: value` manifest field, trimmed.
fn manifest_field_opt< 'a >( wgsl : &'a str, key : &str ) -> Option< &'a str >
{
  let prefix = format!( "//@ {key}:" );
  wgsl.lines()
  .find_map( | line | line.strip_prefix( prefix.as_str() ) )
  .map( str::trim )
}

/// Every line of a repeatable `//@ key: value` manifest field, in file order.
fn manifest_field_all< 'a >( wgsl : &'a str, key : &str ) -> Vec< &'a str >
{
  let prefix = format!( "//@ {key}:" );
  wgsl.lines()
  .filter_map( | line | line.strip_prefix( prefix.as_str() ) )
  .map( str::trim )
  .collect()
}

/// A comma-separated manifest value as trimmed entries, empty when blank.
// Fix(BUG-280): filter out empty segments from a trailing/leading/doubled
// comma, mirroring `src/lib.rs`'s `depends_on_parse`/`tags_parse` fix — this
// function is the compile-time counterpart for both fields, and the
// `chunks_table_matches_each_manifest` test holds its output equal to
// theirs, so the two implementations must not drift.
// Root cause: `split(',').map(trim)` alone still yields an empty segment
// per stray comma; trimming does not remove an already-empty string.
// Pitfall: keep this in sync with the `lib.rs` parsers — they share the
// same manifest grammar by design ( see this file's own module doc ).
fn list_entries( raw : &str ) -> Vec< &str >
{
  if raw.is_empty()
  {
    return Vec::new();
  }
  raw.split( ',' ).map( str::trim ).filter( | entry | !entry.is_empty() ).collect()
}
