[package]
name = "embroidery_tools"
version = "0.1.0"
edition = "2021"
authors = ["Kostiantyn Mysnyk <wandalen@obox.systems>"]
license = "MIT"
repository = "https://github.com/Wandalen/cgtools"
description = "Tools for handling embroidery patterns and operations."
keywords = ["embroidery", "patterns", "tools"]

[lints]
workspace = true

[features]
default = []

[dependencies]
mod_interface = { workspace = true }
byteorder = { workspace = true }
itertools = { workspace = true }
error_tools = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
test_tools = { workspace = true }
