[package]
name = "minwebgl_text_msdf"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Avramenko Yevhenii <yevhenii.av@obox.systems>"
]

[dependencies]
minwebgl = { workspace = true, features = [ "future", "file", "math" ] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }

[dependencies.bytemuck]
workspace = true
features = [ "derive" ]

[dependencies.web-sys]
workspace = true
features = [
  'KeyboardEvent',
]