[package]
name = "minwebgl_text_msdf"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Mysnyk <wandalen@obox.systems>",
  "Avramenko Yevhenii <yevhenii.av@obox.systems>"
]

[dependencies]
minwebgl = { workspace = true, features = [ "future", "file", "math" ] } # Features already here
serde = { workspace = true, features = [ "derive" ] } # Features already here
serde_json = { workspace = true } # Added features back (assuming default features are needed)

[dependencies.bytemuck]
workspace = true
features = [ "derive" ] # Features already here

[dependencies.web-sys]
workspace = true
features = [ # Features already here
  'KeyboardEvent',
]