//! Manifest-driven WGSL shader-chunk composer. Each bundled chunk under the
//! repo-root `shader/` directory is exactly one WGSL function (or, for the
//! vertex stage, one entry point plus the struct type it returns) with its
//! manifest embedded as a leading `//@`-prefixed comment block — the same
//! machine-parsable-attribute convention this ecosystem's playbooks use
//! ( see `playbook.rulebook.md § Structure : Attribute Block` ), with `//`
//! standing in for `#` since that is WGSL's line-comment token. [`compose`]
//! reads every chunk's `//@ depends_on:` line, topologically sorts the given
//! chunks, and concatenates their WGSL bodies dependency-before-dependent —
//! regardless of the order they were passed in — panicking immediately, and
//! naming the offending chunk, on a cyclic or unresolvable dependency.
//! [`try_compose`] is the same sort, non-panicking, for callers ( e.g. a CLI )
//! taking untrusted chunk sets.
//!
//! Applications building a shader out of these chunks select them at
//! compile time rather than absorbing the whole bundled table: [`chunk`]
//! imports one bundled chunk by name in `const` position ( a typo'd name
//! fails the build ), a locally-defined chunk is a plain
//! [`ChunkDescriptor`] literal over `include_str!`, [`dependency_closed`]
//! const-asserts that a hand-selected set is transitively complete, and
//! [`compose_set`] composes the mixed set — imported and local rows alike —
//! straight from descriptor fields. See `readme.md`'s "Importing chunks
//! into an application" section for the full pattern.
//!
//! This crate intentionally has no Rust reimplementation of any chunk's
//! math ( no `hash21`/`value_noise`/`fbm3` Rust ports ). Chunks are a
//! shader-side concept only; the manifest, not a parallel Rust body, is what
//! makes a chunk's interface legible — and since the manifest lives inside
//! the same file as the code it describes, there is only ever one file to
//! open, not two.

mod private
{

  /// One bundled WGSL chunk, as one row of [`CHUNKS`]: every field of its
  /// `//@` manifest header materialized as compile-time data, in manifest
  /// line order, plus its full source text ( manifest header included ).
  ///
  /// Each field mirrors its manifest line verbatim, so neither enumeration
  /// nor [`chunk_get`]'s by-name lookup ever parses a manifest at runtime;
  /// the `chunks_table_matches_each_manifest` test keeps every mirror
  /// honest. The `parse_*` functions remain the way to read manifest fields
  /// off arbitrary ( non-bundled ) chunk text.
  #[ derive( Debug, Clone, Copy, PartialEq, Eq ) ]
  pub struct ChunkDescriptor
  {
    /// The chunk's `//@ name:` manifest value — also its `shader/<name>/` directory and file stem.
    pub name : &'static str,
    /// The chunk's one-line `//@ description:` manifest value.
    pub description : &'static str,
    /// The chunk's `//@ tags:` manifest value as `( group, tag )` pairs, empty when the line is blank.
    pub tags : &'static [ ( &'static str, &'static str ) ],
    /// The chunk's `//@ stage:` manifest value — `Some` only for entry-point chunks ( e.g. `"vertex"` ).
    pub stage : Option< &'static str >,
    /// The chunk's `//@ depends_on:` manifest value as chunk names, empty when the line is blank.
    pub depends_on : &'static [ &'static str ],
    /// One entry per `//@ export:` manifest line, WGSL-syntax signature verbatim, in file order.
    pub exports : &'static [ &'static str ],
    /// The chunk's complete WGSL source text, manifest header included.
    pub wgsl : &'static str,
  }

  // The chunk table itself ( `CHUNKS` + `chunk_get` ) is spliced in from
  // `$OUT_DIR/chunks.rs`, generated by `build.rs` from the `//@` manifest
  // headers in the repo-root `shader/` collection ( row order: the
  // collection-index table in `shader/readme.md` ) — adding a chunk there
  // regenerates the table with no Rust edit here.
  include!( concat!( env!( "OUT_DIR" ), "/chunks.rs" ) );

  // Compile-time selection: `chunk`, `chunk_get_from`, and
  // `dependency_closed` are `const fn`s so an application can select
  // bundled chunks, mix in its own, and validate the result in `const`
  // position — a typo'd name or an incomplete set fails the build, never
  // the first composed frame. `str_eq` exists because `==` on `&str` is
  // not callable in const context.

  const fn str_eq( a : &str, b : &str ) -> bool
  {
    let ( a, b ) = ( a.as_bytes(), b.as_bytes() );
    if a.len() != b.len()
    {
      return false;
    }
    let mut i = 0;
    while i < a.len()
    {
      if a[ i ] != b[ i ]
      {
        return false;
      }
      i += 1;
    }
    true
  }

  /// Imports one bundled chunk by name, by value — the infallible, `const`
  /// counterpart of [`chunk_get`], for selecting just the bundled chunks an
  /// application actually uses instead of absorbing all of [`CHUNKS`]:
  ///
  /// ```
  /// use shader_chunks_core::{ ChunkDescriptor, chunk, dependency_closed, compose_set };
  ///
  /// const MY_CHUNKS : &[ ChunkDescriptor ] =
  /// &[
  ///   chunk( "hash21" ),
  ///   chunk( "value_noise" ),
  /// ];
  /// const _ : () = assert!( dependency_closed( MY_CHUNKS ) );
  ///
  /// let wgsl = compose_set( MY_CHUNKS );
  /// assert!( wgsl.contains( "fn value_noise(" ) );
  /// ```
  ///
  /// # Panics
  ///
  /// Panics when `name` is not a bundled chunk — in `const` position ( the
  /// intended use ) that is a compile error at the call site, so a typo'd
  /// import can never survive to runtime.
  #[ must_use ]
  pub const fn chunk( name : &str ) -> ChunkDescriptor
  {
    match chunk_get_from( CHUNKS, name )
    {
      Some( descriptor ) => *descriptor,
      None => panic!( "unknown chunk name — see CHUNKS for the bundled set" ),
    }
  }

  /// Resolves one chunk by name from a caller-supplied set — the same
  /// lookup as [`chunk_get`], but over any set ( imported, local, or
  /// mixed ) instead of the bundled table, and `const`, so selecting out of
  /// a mixed set works in `const` position too. Linear over `set` — free
  /// during compile-time evaluation; prefer [`chunk_get`] for runtime
  /// lookup of bundled chunks.
  #[ must_use ]
  pub const fn chunk_get_from<'a>( set : &'a [ ChunkDescriptor ], name : &str ) -> Option< &'a ChunkDescriptor >
  {
    let mut i = 0;
    while i < set.len()
    {
      if str_eq( set[ i ].name, name )
      {
        return Some( &set[ i ] );
      }
      i += 1;
    }
    None
  }

  /// True when every `depends_on` entry of every chunk in `set` names a
  /// chunk that is itself in `set` — the precondition [`compose_set`] needs
  /// to succeed. `const`, so a hand-selected set is validated at compile
  /// time: `const _ : () = assert!( dependency_closed( MY_CHUNKS ) );`
  /// fails the build, naming this assert, when an import was forgotten.
  #[ must_use ]
  pub const fn dependency_closed( set : &[ ChunkDescriptor ] ) -> bool
  {
    let mut i = 0;
    while i < set.len()
    {
      let deps = set[ i ].depends_on;
      let mut d = 0;
      while d < deps.len()
      {
        if chunk_get_from( set, deps[ d ] ).is_none()
        {
          return false;
        }
        d += 1;
      }
      i += 1;
    }
    true
  }

  /// Compares every descriptor field of `chunk` against what the `parse_*`
  /// functions read from its own `wgsl` manifest, returning one message per
  /// drifted field — empty means descriptor and manifest agree. The bundled
  /// table is held to this by this crate's own tests; a crate defining
  /// local chunks calls it from one test per local chunk to get the same
  /// no-silent-drift guarantee.
  ///
  /// # Panics
  ///
  /// Panics when `chunk.wgsl` lacks a mandatory manifest line, per the
  /// `parse_*` functions this delegates to.
  #[ must_use ]
  pub fn manifest_mismatches( chunk : &ChunkDescriptor ) -> Vec< String >
  {
    let name = chunk.name;
    let mut mismatches = Vec::new();
    let manifest_name = parse_name( chunk.wgsl );
    if name != manifest_name
    {
      mismatches.push( format!( "chunk `{name}`: descriptor name `{name}` != manifest `//@ name:` value `{manifest_name}`" ) );
    }
    let manifest_description = parse_description( chunk.wgsl );
    if chunk.description != manifest_description
    {
      mismatches.push( format!
      (
        "chunk `{name}`: descriptor description {:?} != manifest `//@ description:` value {manifest_description:?}",
        chunk.description
      ));
    }
    if parse_tags( chunk.wgsl ) != chunk.tags
    {
      mismatches.push( format!
      (
        "chunk `{name}`: descriptor tags {:?} != manifest `//@ tags:` value {:?}",
        chunk.tags,
        parse_tags( chunk.wgsl )
      ));
    }
    if chunk.stage != parse_stage( chunk.wgsl )
    {
      mismatches.push( format!
      (
        "chunk `{name}`: descriptor stage {:?} != manifest `//@ stage:` value {:?}",
        chunk.stage,
        parse_stage( chunk.wgsl )
      ));
    }
    if parse_depends_on( chunk.wgsl ) != chunk.depends_on
    {
      mismatches.push( format!
      (
        "chunk `{name}`: descriptor depends_on {:?} != manifest `//@ depends_on:` value {:?}",
        chunk.depends_on,
        parse_depends_on( chunk.wgsl )
      ));
    }
    if parse_exports( chunk.wgsl ) != chunk.exports
    {
      mismatches.push( format!
      (
        "chunk `{name}`: descriptor exports {:?} != manifest `//@ export:` lines {:?}",
        chunk.exports,
        parse_exports( chunk.wgsl )
      ));
    }
    mismatches
  }

  // A chunk's `//@ key: value` header lines are its manifest. `manifest_field`
  // reads a mandatory single-line field ( `name`, `depends_on`, `description`,
  // `tags` ); `manifest_field_opt` reads an optional single-line field
  // ( `stage`, vertex-only ); `manifest_field_all` collects every line for a
  // repeatable field ( `export`, one or more per chunk ). This crate's tests
  // ( `tests/shader_chunks_core_test.rs` ) cross-check `export` against the real
  // WGSL body, so it can't silently drift.

  fn manifest_field<'a>( wgsl : &'a str, key : &str ) -> &'a str
  {
    let prefix = format!( "//@ {key}:" );
    wgsl.lines()
    .find_map( | line | line.strip_prefix( prefix.as_str() ) )
    .unwrap_or_else( || panic!( "chunk missing required `//@ {key}:` header line:\n{wgsl}" ) )
    .trim()
  }

  fn manifest_field_opt<'a>( wgsl : &'a str, key : &str ) -> Option< &'a str >
  {
    let prefix = format!( "//@ {key}:" );
    wgsl.lines()
    .find_map( | line | line.strip_prefix( prefix.as_str() ) )
    .map( str::trim )
  }

  fn manifest_field_all<'a>( wgsl : &'a str, key : &str ) -> Vec< &'a str >
  {
    let prefix = format!( "//@ {key}:" );
    wgsl.lines()
    .filter_map( | line | line.strip_prefix( prefix.as_str() ) )
    .map( str::trim )
    .collect()
  }

  /// Reads the chunk's `//@ name:` manifest line.
  ///
  /// # Panics
  ///
  /// Panics if the chunk has no `//@ name:` header line.
  #[ must_use ]
  pub fn parse_name( wgsl : &str ) -> &str
  {
    manifest_field( wgsl, "name" )
  }

  /// Reads the chunk's `//@ depends_on:` manifest line as a list of chunk
  /// names ( empty when the value is empty ).
  ///
  /// # Panics
  ///
  /// Panics if the chunk has no `//@ depends_on:` header line.
  #[ must_use ]
  pub fn parse_depends_on( wgsl : &str ) -> Vec< &str >
  {
    let raw = manifest_field( wgsl, "depends_on" );
    if raw.is_empty()
    {
      return Vec::new();
    }
    raw.split( ',' ).map( str::trim ).collect()
  }

  /// Reads the chunk's `//@ description:` manifest line.
  ///
  /// # Panics
  ///
  /// Panics if the chunk has no `//@ description:` header line.
  #[ must_use ]
  pub fn parse_description( wgsl : &str ) -> &str
  {
    manifest_field( wgsl, "description" )
  }

  /// Reads the chunk's `//@ stage:` manifest line, if present ( only the
  /// vertex-stage chunk declares one — ordinary function chunks have none ).
  #[ must_use ]
  pub fn parse_stage( wgsl : &str ) -> Option< &str >
  {
    manifest_field_opt( wgsl, "stage" )
  }

  /// Reads every `//@ export:` manifest line, in file order ( a chunk may
  /// export more than one symbol, e.g. a struct plus the function that
  /// returns it ).
  #[ must_use ]
  pub fn parse_exports( wgsl : &str ) -> Vec< &str >
  {
    manifest_field_all( wgsl, "export" )
  }

  /// Reads the chunk's `//@ tags:` manifest line as a list of `(group, tag)`
  /// pairs ( empty when the value is empty ).
  ///
  /// # Panics
  ///
  /// Panics if the chunk has no `//@ tags:` header line, or if an entry has
  /// no `:` separator.
  #[ must_use ]
  pub fn parse_tags( wgsl : &str ) -> Vec< ( &str, &str ) >
  {
    let raw = manifest_field( wgsl, "tags" );
    if raw.is_empty()
    {
      return Vec::new();
    }
    raw.split( ',' )
    .map( str::trim )
    .map( | entry | entry.split_once( ':' )
      .unwrap_or_else( || panic!( "malformed `//@ tags:` entry (expected `group:tag`): {entry:?}" ) ) )
    .collect()
  }

  struct ParsedChunk< 'a >
  {
    name : &'a str,
    depends_on : Vec< &'a str >,
    wgsl : &'a str,
  }

  /// Error returned by [`try_compose`] instead of panicking.
  #[ derive( Debug, Clone, PartialEq, Eq ) ]
  pub enum ComposeError
  {
    /// A dependency cycle was found among the given chunks. Carries the
    /// visiting-stack trail ( `"[...] -> name"` ) that closed the cycle.
    CyclicDependency( String ),
    /// A chunk's `//@ depends_on:` names a chunk not present in the given set.
    MissingDependency
    {
      /// The chunk whose `depends_on` line named the missing chunk.
      chunk : String,
      /// The depended-on chunk name that was not passed to `try_compose`.
      missing : String,
    },
  }

  impl std::fmt::Display for ComposeError
  {
    fn fmt( &self, f : &mut std::fmt::Formatter< '_ > ) -> std::fmt::Result
    {
      match self
      {
        Self::CyclicDependency( trail ) => write!( f, "cyclic shader-chunk dependency: {trail}" ),
        Self::MissingDependency { chunk, missing } =>
        write!( f, "chunk `{chunk}` depends on `{missing}`, which was not passed to compose()" ),
      }
    }
  }

  impl std::error::Error for ComposeError {}

  /// Topologically sorts `chunks` by each one's header-declared `depends_on`
  /// and concatenates their WGSL bodies in that order, dependency before
  /// dependent, regardless of the order they were passed in.
  ///
  /// # Panics
  ///
  /// Panics, naming the offending chunk, on a dependency cycle or a
  /// `depends_on` entry not present in `chunks` — both are authoring mistakes
  /// in a chunk's header ( or in the set passed to `compose` ), not states a
  /// correctly-authored composition can reach. Use [`try_compose`] instead
  /// when `chunks` is not already trusted to be internally consistent.
  #[ must_use ]
  pub fn compose( chunks : &[ &str ] ) -> String
  {
    try_compose( chunks ).unwrap_or_else( | err | panic!( "{err}" ) )
  }

  /// Non-panicking twin of [`compose`]: same topological sort over `chunks`,
  /// but reports a dependency cycle or unresolved dependency as an [`Err`]
  /// instead of panicking — for callers ( e.g. a CLI ) taking untrusted chunk
  /// sets where a panic is the wrong failure mode.
  ///
  /// # Errors
  ///
  /// Returns [`ComposeError::CyclicDependency`] on a dependency cycle, or
  /// [`ComposeError::MissingDependency`] when a `depends_on` entry names a
  /// chunk not present in `chunks`.
  pub fn try_compose( chunks : &[ &str ] ) -> Result< String, ComposeError >
  {
    let entries : Vec< ParsedChunk< '_ > > = chunks.iter()
    .map( | &wgsl | ParsedChunk { name : parse_name( wgsl ), depends_on : parse_depends_on( wgsl ), wgsl } )
    .collect();
    sort_and_join( &entries )
  }

  /// [`compose`] over a set of [`ChunkDescriptor`]s — imported via
  /// [`chunk`], locally defined, or mixed — reading each descriptor's own
  /// `name` and `depends_on` fields directly, with no manifest re-parsing.
  ///
  /// # Panics
  ///
  /// Panics, naming the offending chunk, on a dependency cycle or a
  /// `depends_on` entry not present in `set` — same contract as
  /// [`compose`]. `const _ : () = assert!( dependency_closed( SET ) );`
  /// rules the missing-dependency case out at compile time; use
  /// [`try_compose_set`] instead when `set` is not trusted.
  #[ must_use ]
  pub fn compose_set( set : &[ ChunkDescriptor ] ) -> String
  {
    try_compose_set( set ).unwrap_or_else( | err | panic!( "{err}" ) )
  }

  /// Non-panicking twin of [`compose_set`], same as [`try_compose`] is to
  /// [`compose`].
  ///
  /// # Errors
  ///
  /// Returns [`ComposeError::CyclicDependency`] on a dependency cycle, or
  /// [`ComposeError::MissingDependency`] when a descriptor's `depends_on`
  /// names a chunk not present in `set`.
  pub fn try_compose_set( set : &[ ChunkDescriptor ] ) -> Result< String, ComposeError >
  {
    let entries : Vec< ParsedChunk< '_ > > = set.iter()
    .map( | chunk | ParsedChunk { name : chunk.name, depends_on : chunk.depends_on.to_vec(), wgsl : chunk.wgsl } )
    .collect();
    sort_and_join( &entries )
  }

  // Shared sort core of `try_compose` ( entries parsed from raw text ) and
  // `try_compose_set` ( entries read from descriptor fields ): topological
  // order via `visit`, then dependency-before-dependent concatenation.
  fn sort_and_join( entries : &[ ParsedChunk< '_ > ] ) -> Result< String, ComposeError >
  {
    let mut ordered : Vec< &ParsedChunk< '_ > > = Vec::with_capacity( entries.len() );
    let mut visiting : Vec< &str > = Vec::new();

    for entry in entries
    {
      visit( entry.name, None, entries, &mut visiting, &mut ordered )?;
    }

    Ok( ordered.iter().map( | e | e.wgsl ).collect::< Vec< _ > >().join( "\n\n" ) )
  }

  // Two lifetimes: `'a` is the borrowed WGSL source text ( outlives this call,
  // e.g. `'static` for the bundled consts ); `'e` is the local `entries`
  // slice built in `try_compose`. `ordered` collects `&'e ParsedChunk<'a>`
  // directly instead of names, so the final join needs no second name->chunk
  // lookup ( which would be a spurious, clippy-flagged `.expect()` — every
  // name in `ordered` already has its chunk in hand at push time ).
  fn visit<'a, 'e>
  (
    name : &'a str,
    required_by : Option< &'a str >,
    entries : &'e [ ParsedChunk< 'a > ],
    visiting : &mut Vec< &'a str >,
    ordered : &mut Vec< &'e ParsedChunk< 'a > >,
  ) -> Result< (), ComposeError >
  {
    if ordered.iter().any( | e | e.name == name )
    {
      return Ok( () );
    }
    if visiting.contains( &name )
    {
      return Err( ComposeError::CyclicDependency( format!( "{visiting:?} -> {name}" ) ) );
    }

    let Some( entry ) = entries.iter().find( | e | e.name == name ) else
    {
      return Err( ComposeError::MissingDependency
      {
        chunk : required_by.unwrap_or( name ).to_string(),
        missing : name.to_string(),
      });
    };

    visiting.push( name );
    for &dep in &entry.depends_on
    {
      visit( dep, Some( name ), entries, visiting, ordered )?;
    }
    visiting.pop();
    ordered.push( entry );
    Ok( () )
  }

}

::mod_interface::mod_interface!
{
  own use ChunkDescriptor;
  own use CHUNKS;
  own use chunk_get;
  own use chunk;
  own use chunk_get_from;
  own use dependency_closed;
  own use manifest_mismatches;
  own use compose_set;
  own use try_compose_set;
  own use parse_name;
  own use parse_depends_on;
  own use parse_description;
  own use parse_stage;
  own use parse_exports;
  own use parse_tags;
  own use ComposeError;
  own use compose;
  own use try_compose;
}
